### PR TITLE
Authentication and Post Project

### PR DESCRIPTION
**Pull request by taiwo2**
Built with 
- SASS
- Add devise to my Gemfile
- SQLite
- ruby on rails

### CODE REVIEW

**Review by teekaytech — CHANGES_REQUESTED** [review]
# Status :Invalid Review Request :heavy_multiplication_x: 

**Hi team, congratulations on submitting your first code review request. Unfortunately, I cannot review your project.**

* * *
- [ ] **You should use Git Flow in this project.**
- The main/master branch is missing in your repository.
This is wrong. Your master/main branch should be present with a single commit (initial commit) while all other commits are to be done on the feature branch (youtube-1 in your case).
- For better understanding, please take a step back and read a lesson [here](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/).

**Please note that this Code Review Request will be marked as invalid, so please submit a new one once you are ready!**

* * * 
**Taofeek Olalere
[Twitter](https://twitter.com/ola_lere) | [Github](https://github.com/teekaytech) | @taofeekolalere on Slack**
__Happy Coding :smiley:__

**Comment by taiwo2** [comment]
Kindly check and flow the git flow.we are to use development not master or main branch.use microverse requirements page for project and kindly do the needful. Waiting for your response

**Review by peterrobert — CHANGES_REQUESTED** [review]
### INVALID 🛑 

Hello, @taiwo2  great work submitting your project for a review. However, just like stated by the previous TSE, your git-flow is wrong. Kindly check the points below ⬇️ 

At this point, you should have three branches:

1.  Main branch
2. Development branch
3.  Authentication branch.

Then make the development branch your default branch. 

What you have done is that you have the development branch and the authentication branch. But you are missing the main branch.

I hope the explanation above helps. Also, use this [article](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/)
to understand more.

### if you have any question reach me on slack @peterrobert

### HAPPY CODING

**Comment by taiwo2** [comment]
I have been doing projects without the main branch and it got approved not even two projects. the main branch does not serve any purpose on my repository. its serves as the same purpose feature branch. can you explain the need for the main branch?.kindly read microverse gitflow requirement properly.

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**INVALID** :red_circle: 
Hi team, Good introduction!
You should use Git Flow in this project.

- [ ] Create a new branch called "Main branch" as you should have three branches ([git-flow](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59882084/))

HAPPY CODING
Rindra Josia

**Comment by taiwo2** [comment]
creating the main branch serves no purpose. can you explain the use of the main branch when I have already use the authentication branch

**Review by rindrajosia — CHANGES_REQUESTED** [review]
**Changes Required!**
Hello!!
You did a very good job.
However, to move forward you have to make some changes:

- [ ] [REQUIRED] **The application layout** has Sign in / Sign out links (So they are not manually repeated in every view) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/sign_in_out_link_requirement.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/49722686/))
- [ ] [REQUIRED] Add screenshot in your readme file

Happy coding
Rindra Josia

**Review by ebeagusamuel — APPROVED** [review]
# Project Approved :100:
### Congratulations, :clap: , this project is now approved. You can go ahead and merge this branch and also good luck with the next project.
slack(@ebeagusamuel)

**Pull request merged**
